mode: sample
visible_gpus: '0'
task: AMP
arch: cvqvae
data_path: ../logs/lssamp_amp/train/epoch_128_index   # change according the best epoch
log_dir: ../logs/lssamp_amp
data_process: sample_index
loss_func: cvqvae
test_from: ../models/lssamp_amp/model_best.pt

batch_size: 1
code_book: 4
randomnum: 3
mask_ratio: 0.1
max_length: 32
max_tgt_len: 32
test_batch_size: 5000

step: 0
# seed: 666
sample: top
block_trigram: True
seq_reverse: False
